name: readershaven_app
description: "Reader's Haven"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  google_nav_bar: ^5.0.7
  path: ^1.9.0
  file_picker: ^8.1.4
  syncfusion_flutter_pdfviewer: ^27.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  path_provider: ^2.1.5


flutter:
  uses-material-design: true
  assets:
      - assets/
